/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import operaciones.Alumno;
import operaciones.AlumnosOp;

/**
 *
 * @author alan6
 */
public class FAlumnos extends javax.swing.JFrame {

    //Variables
    AlumnosOp alumnosOp;
    Alumno alumno;

    public FAlumnos() {
        initComponents();
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnBaja.setEnabled(false);
        txtActivo(false);

        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(this);
    }

    public FAlumnos(Alumno alumno) {
        this();
        this.alumno = alumno;
        txtControl.setText(alumno.getNumControl());
        txtNombre.setText(alumno.getNombre());
        txtApellidos.setText(alumno.getApellido());
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");

        btnActualizar.setEnabled(true);
        btnBaja.setEnabled(true);
        btnNuevo.setEnabled(false);
        txtActivo(true);

    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtControl.setText("");
    }

    void txtActivo(boolean accion) {
        txtNombre.setEnabled(accion);
        txtApellidos.setEnabled(accion);
        txtTelefono.setEnabled(accion);
        txtDireccion.setEnabled(accion);
        txtEmail.setEnabled(accion);
        txtControl.setEnabled(accion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AgregAlum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnBaja = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtControl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContenedorPanel.setBackground(new java.awt.Color(0, 204, 204));
        ContenedorPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContenedorPanelStateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ContenedorPanel.addTab("Ver Alumnos", jPanel1);

        AgregAlum.setBackground(new java.awt.Color(0, 102, 102));
        AgregAlum.setPreferredSize(new java.awt.Dimension(700, 700));
        AgregAlum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre :");
        AgregAlum.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 205, -1, -1));

        jLabel2.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos :");
        AgregAlum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 245, -1, -1));

        txtNombre.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        AgregAlum.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 205, 200, -1));

        txtApellidos.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        AgregAlum.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, -1));

        jLabel4.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Colonia:");
        AgregAlum.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        AgregAlum.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 198, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        AgregAlum.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 200, -1));

        jLabel5.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calle:");
        AgregAlum.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero:");
        AgregAlum.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        txtEmail.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        AgregAlum.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 200, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 70));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBaja.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnBaja.setText("Dar de Baja ");
        btnBaja.setBorder(null);
        btnBaja.setContentAreaFilled(false);
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        jPanel4.add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 43));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document_add.png"))); // NOI18N
        btnNuevo.setText("Nuevo Alumno");
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, 43));

        btnGuardar.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setText("Guardar Alumno");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 150, 43));

        btnActualizar.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document_edit.png"))); // NOI18N
        btnActualizar.setText("Actualizar Alumno");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 190, 43));

        AgregAlum.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 998, -1));

        txtControl.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        AgregAlum.add(txtControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 200, -1));

        jLabel10.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Num. Control:");
        AgregAlum.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel20.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpg"))); // NOI18N
        AgregAlum.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        ContenedorPanel.addTab("Agregar Alumno", AgregAlum);
        AgregAlum.getAccessibleContext().setAccessibleName("");

        getContentPane().add(ContenedorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta el nombre del Alumno a registrar");
            return;
        }
        if (txtApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta el apellido del Alumno a registrar");
            return;
        }
        if (txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta el numero de telefono del Alumno a registrar");
            return;
        }
        if (txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta la direccion del Alumno a registrar");
            return;
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de actualizar al Alumno  ?");
        if (opcion == JOptionPane.YES_OPTION) {

            if (txtNombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta el nombre del Alumno a registrar");
                return;
            }
            if (txtApellidos.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta el apellido del Alumno a registrar");
                return;
            }

            if (txtTelefono.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta el numero de telefono del Alumno a registrar");
                return;
            }
            if (txtDireccion.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta la direccion del Alumno a registrar");
                return;
            }

            alumnosOp = new AlumnosOp();

            alumnosOp.actualizarAlumno(alumno.getId(), alumno);
            limpiar();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:

        txtActivo(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de dar de Baja al Alumno " + txtNombre.getText() + " con Matricula " + txtControl.getText() + " ?");
        if (opcion == JOptionPane.YES_OPTION) {
            alumnosOp = new AlumnosOp();

            alumnosOp.eliminarAlumno(alumno.getId());
            limpiar();
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void ContenedorPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContenedorPanelStateChanged

        
    }//GEN-LAST:event_ContenedorPanelStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregAlum;
    private javax.swing.JTabbedPane ContenedorPanel;
    public static javax.swing.JButton btnActualizar;
    public static javax.swing.JButton btnBaja;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JTextField txtControl;
    public static javax.swing.JTextArea txtDireccion;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
